import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'

import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="nav">
          <Link className="btn " href="/">home</Link>
          <Link className="btn" href="/posts">posts</Link>
         
        </nav>
        
        {children}</body>
    </html>
  );
}
